apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

commonLabels:
  environment: production

replicas:
- name: bankapp
  count: 3  # Multiple replicas for production

images:
- name: bankapp
  newName: ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/bankapp
  newTag: production-latest