replicaCount: 1

image:
  repository: ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/bankapp
  tag: staging-latest

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  hosts:
    - host: bankapp-staging.example.com
      paths:
        - path: /
          pathType: Prefix

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "staging"
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: host
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: database
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: password

autoscaling:
  enabled: false