apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml

commonLabels:
  app: bankapp
  version: "1.0"

images:
- name: bankapp
  newTag: latest